# Generated by Django 2.2.16 on 2021-08-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ta3leemreminder',
            options={'verbose_name': 'Ta3leem Reminder', 'verbose_name_plural': 'Ta3leem Reminders'},
        ),
        migrations.RenameField(
            model_name='ta3leemreminder',
            old_name='reminder_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='ta3leemreminder',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='ta3leemreminder',
            name='course_id',
        ),
        migrations.AddField(
            model_name='ta3leemreminder',
            name='identifier',
            field=models.CharField(db_index=True, default=1, help_text='Column Used to store identifier of reminder type', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ta3leemreminder',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ta3leemreminder',
            name='send_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ta3leemreminder',
            name='type',
            field=models.CharField(choices=[('course_start_date', 'Course Start Date'), ('course_start_end', 'Course End Date'), ('exam_start_date', 'Exam Start Date'), ('exam_end_date', 'Exam End Date'), ('live_class', 'Live Class'), ('course_important_date', 'Course Important Date'), ('individual_user', 'User')], help_text='Select the reminder type', max_length=24),
        ),
    ]
