# Generated by Django 2.2.16 on 2021-09-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_calendar', '0003_auto_20210826_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta3leemreminder',
            name='type',
            field=models.CharField(choices=[('course_start_date', 'Course Start Date'), ('course_end_date', 'Course End Date'), ('exam_start_date', 'Exam Start Date'), ('exam_end_date', 'Exam End Date'), ('live_class', 'Live Class'), ('course_important_date', 'Course Important Date')], help_text='Select the reminder type', max_length=24),
        ),
    ]
