# Generated by Django 2.2.16 on 2021-12-01 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taleem_calendar', '0004_auto_20210915_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event', max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('time', models.DateTimeField(help_text='Time of the event to show on calendar')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calender_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Calendar Events',
                'verbose_name': 'Calender Event',
            },
        ),
    ]
