# Generated by Django 2.2.16 on 2022-06-14 21:38

from django.db import migrations, models
import openedx.core.djangoapps.content.course_overviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0023_auto_20201216_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='appstore_id',
            field=models.UUIDField(default=openedx.core.djangoapps.content.course_overviews.models.uuid_hex, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='appstore_id',
            field=models.UUIDField(default=openedx.core.djangoapps.content.course_overviews.models.uuid_hex),
        ),
    ]
