# Generated by Django 2.2.16 on 2022-06-14 21:47

from django.db import migrations, models
import openedx.core.djangoapps.content.course_overviews.models


class Migration(migrations.Migration):
    dependencies = [
        ('course_overviews', '0025_auto_20220615_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverview',
            name='appstore_id',
            field=models.UUIDField(default=openedx.core.djangoapps.content.course_overviews.models.uuid_hex, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcourseoverview',
            name='appstore_id',
            field=models.UUIDField(db_index=True, default=openedx.core.djangoapps.content.course_overviews.models.uuid_hex),
        ),
    ]

