# Generated by Django 2.2.16 on 2021-01-24 06:59

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('question_bank', models.SlugField(max_length=255)),
                ('question', opaque_keys.edx.django.models.UsageKeyField(max_length=255)),
                ('tag_type', models.CharField(choices=[('chapter', 'chapter'), ('topic', 'topic'), ('difficulty_level', 'difficulty_level'), ('learning_output', 'learning_output')], max_length=255)),
                ('tag', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
