# Generated by Django 2.2.16 on 2020-12-04 10:12

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0006_auto_20201123_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_bank', models.SlugField(max_length=255)),
                ('question', opaque_keys.edx.django.models.UsageKeyField(max_length=255)),
                ('tag_type', models.CharField(choices=[('chapter', 'chapter'), ('topic', 'topic')], max_length=255)),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
    ]
