# Generated by Django 2.2.16 on 2021-01-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0008_auto_20210102_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedexamsettings',
            name='allotted_time',
            field=models.CharField(default='01:00', max_length=255),
        ),
    ]
