# Generated by Django 2.2.16 on 2021-01-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0009_timedexamsettings_allotted_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimedExamSettings',
        ),
    ]
