# Generated by Django 2.2.16 on 2021-01-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0010_delete_timedexamsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionTags',
        ),
    ]
