# Generated by Django 2.2.16 on 2021-04-01 07:55

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255, unique=True)),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('currency', models.CharField(default='iqd', max_length=8)),
            ],
            options={
                'verbose_name': 'Course Price',
                'verbose_name_plural': 'Course Prices',
            },
        ),
        migrations.AlterModelOptions(
            name='ipaddresswhitelist',
            options={'verbose_name': 'IP Address Whitelist', 'verbose_name_plural': 'IP Address Whitelist'},
        ),
    ]
