# Generated by Django 2.2.16 on 2021-04-16 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0004_auto_20210408_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddresswhitelist',
            name='mask',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)]),
        ),
        migrations.AddField(
            model_name='ipaddresswhitelist',
            name='type',
            field=models.CharField(choices=[('single_ip', 'Single IP Address'), ('subnet', 'Subnet')], default='single_ip', max_length=25),
        ),
    ]
