# Generated by Django 2.2.16 on 2022-08-26 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_alter_student_course_enrollment_options'),
        ('payment_gateway', '0007_auto_20210618_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherusage',
            name='enrollment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_usages', to='student.CourseEnrollment'),
        ),
    ]
