# Generated by Django 2.2.16 on 2021-03-08 11:34

from django.db import migrations


def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    groups = [u'Ta3leem Teacher', u'Ta3leem Staff', u'Verification Specialist']

    for group in groups:
        Group.objects.get_or_create(
            name=group
        )


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            u'Ta3leem Teacher',
            u'Ta3leem Staff',
            u'Verification Specialist',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('taleem', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
