# Generated by Django 2.2.16 on 2021-03-11 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_organization', '0002_taleem_organization_verbose_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taleem', '0002_auto_20210308_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ta3leemUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('', '------'), ('teacher', 'Teacher'), ('student', 'Student')], default='', max_length=32)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taleem_organization.College')),
                ('department', models.ManyToManyField(blank=True, to='taleem_organization.Department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taleem_organization.TaleemOrganization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ta3leem_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ta3leem User Profile',
                'verbose_name_plural': 'Ta3leem User Profile',
            },
        ),
    ]
