# Generated by Django 2.2.16 on 2021-05-18 06:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('taleem', '0004_secondpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta3leemuserprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
