# Generated by Django 2.2.16 on 2021-08-05 10:41

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taleem', '0006_courserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta3leemuserprofile',
            name='extra_settings',
            field=jsonfield.fields.JSONField(default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, help_text='Store Extra Settings for User', load_kwargs={}),
        ),
    ]
