# Generated by Django 2.2.16 on 2021-08-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleem', '0007_ta3leemuserprofile_extra_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta3leemuserprofile',
            name='user_ip_address',
            field=models.GenericIPAddressField(blank=True, default=None, null=True),
        ),
    ]
