# Generated by Django 2.2.16 on 2021-09-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleem', '0008_ta3leemuserprofile_user_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta3leemuserprofile',
            name='grade',
            field=models.CharField(choices=[('NA', 'Not Applicable'), ('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3'), ('G4', 'Grade 4'), ('G5', 'Grade 5'), ('G6', 'Grade 6'), ('G7', 'Grade 7'), ('G8', 'Grade 8'), ('G9', 'Grade 9'), ('GA', 'Grade 10'), ('GB', 'Grade 11'), ('GC', 'Grade 12')], default='NA', max_length=2, verbose_name='Standard Code'),
        ),
    ]
