# Generated by Django 2.2.16 on 2021-10-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleem', '0009_adding_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('attempted_at', models.DateTimeField()),
            ],
        ),
    ]
