# Generated by Django 2.2.16 on 2021-11-18 07:21

from django.db import migrations, models
import openedx.custom.taleem.models


class Migration(migrations.Migration):

    dependencies = [
        ('taleem', '0010_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='attempted_at',
            field=models.DateTimeField(default=openedx.custom.taleem.models.utc_now_with_tz_info),
        ),
    ]
