# Generated by Django 2.2.16 on 2021-11-23 06:13

from django.db import migrations, models
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taleem', '0011_auto_20211118_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta3leemuserprofile',
            name='is_tashgheel_user',
            field=models.BooleanField(default=False, help_text='Is user from Tashgeel?'),
        ),
        migrations.AlterField(
            model_name='ta3leemuserprofile',
            name='extra_settings',
            field=jsonfield.fields.JSONField(blank=True, default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, help_text='Store Extra Settings for User', load_kwargs={}, null=True),
        ),
    ]
