# Generated by Django 2.2.16 on 2022-02-20 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleem', '0012_auto_20211123_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta3leemuserprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taleem_organization.TaleemOrganization'),
        ),
        migrations.AlterField(
            model_name='ta3leemuserprofile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=32),
        ),
    ]
