# Generated by Django 2.2.16 on 2022-03-23 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taleem', '0013_auto_20220221_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAccountRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('declined', 'Declined'), ('approved', 'Approved'), ('applied', 'Applied')], default='applied', max_length=10, verbose_name='Request State')),
                ('state_changed_at', models.DateTimeField(auto_now_add=True, help_text='The date when state was last updated', verbose_name='state last updated')),
                ('note', models.CharField(blank=True, help_text='Optional notes about this user (for example, why access was denied)', max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_account_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Account Request',
                'verbose_name_plural': 'Teacher Account Requests',
            },
        ),
    ]
