# Generated by Django 2.2.16 on 2022-06-15 07:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import openedx.custom.taleem.models
import versionfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taleem', '0014_teacheraccountrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('mode', models.CharField(choices=[('test', 'Testing'), ('prod', 'Production')], default='test', max_length=4)),
                ('version', versionfield.fields.VersionField()),
                ('ipa', models.FileField(upload_to=openedx.custom.taleem.models.mobile_app_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ipa'])])),
                ('display_image', models.ImageField(upload_to=openedx.custom.taleem.models.mobile_app_path)),
                ('full_size_image', models.ImageField(upload_to=openedx.custom.taleem.models.mobile_app_path)),
                ('downloads', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Mobile Apps',
                'verbose_name': 'Mobile App',
                'get_latest_by': 'modified',
                'unique_together': {('mode', 'version')},
            },
        ),
    ]
