# Generated by Django 2.2.16 on 2022-06-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taleem', '0016_mobile_app_force_update'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mobileapp',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mobileapp',
            name='downloads',
        ),
        migrations.RemoveField(
            model_name='mobileapp',
            name='mode',
        ),
    ]
