# Generated by Django 2.2.16 on 2022-08-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleem', '0017_remove_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta3leemuserprofile',
            name='is_test_user',
            field=models.BooleanField(default=False, help_text='Is this a test user?'),
        ),
    ]
