# Generated by Django 2.2.16 on 2022-10-12 07:57

from django.db import migrations, models
import versionfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taleem', '0019_auto_20220901_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapp',
            name='android_force_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='android_version',
            field=versionfield.fields.VersionField(default='1.0.0'),
            preserve_default=False,
        ),
    ]
