# Generated by Django 2.2.16 on 2022-11-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleem', '0022_drop_can_create_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta3leemuserprofile',
            name='can_use_normal_browser',
            field=models.BooleanField(default=False, help_text='If test user who can access the lms in normal browser?'),
        ),
    ]
