# Generated by Django 2.2.16 on 2021-04-07 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import openedx.core.djangoapps.user_authn.utils
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taleem', '0004_secondpassword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(null=True)),
                ('scheduled_on', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField(default=60)),
                ('seats', models.PositiveSmallIntegerField(default=150)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('meeting_password', models.CharField(default=openedx.core.djangoapps.user_authn.utils.generate_password, max_length=255)),
                ('stage', models.CharField(choices=[('sd', 'Scheduled'), ('rg', 'Running'), ('ed', 'Ended')], db_index=True, default='sd', max_length=2)),
                ('moderator', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='taleem.Ta3leemUserProfile')),
            ],
            options={
                'verbose_name_plural': 'Live Classes',
                'ordering': ('-scheduled_on',),
                'verbose_name': 'Live Class',
            },
        ),
        migrations.CreateModel(
            name='LiveClassBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='live_class.LiveClass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'live_class')},
                'verbose_name_plural': 'Live Class Bookings',
                'verbose_name': 'Live Class Booking',
            },
        ),
    ]
