# Generated by Django 2.2.16 on 2021-05-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0002_liveclassattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclassattendance',
            name='left_at',
            field=models.DateTimeField(null=True),
        ),
    ]
