# Generated by Django 2.2.16 on 2021-05-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0003_auto_20210524_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='class_type',
            field=models.CharField(choices=[('pr', 'Private'), ('pi', 'Public at Institution Level'), ('pu', 'Public')], default='pu', max_length=2),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='stage',
            field=models.CharField(choices=[('ur', 'Under Review'), ('de', 'Declined'), ('sd', 'Scheduled'), ('rg', 'Running'), ('ed', 'Ended')], db_index=True, default='ur', max_length=2),
        ),
    ]
