# Generated by Django 2.2.16 on 2021-06-08 10:57

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_gateway', '0006_auto_20210608_1357'),
        ('live_class', '0004_auto_20210527_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClassPaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Amount Paid')),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_history', to='live_class.LiveClass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='live_class_payment', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='voucher_usages_for_live_class', to='payment_gateway.Voucher')),
            ],
            options={
                'verbose_name': 'Live Class Payment History',
                'verbose_name_plural': 'Live Class Payment Histories',
            },
        ),
    ]
