# Generated by Django 2.2.16 on 2021-06-24 16:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0005_liveclasspaymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='class_type',
            field=models.CharField(choices=[('pr', 'Private'), ('pi', 'Public at Institution Level'), ('pu', 'Public')], default='pu', max_length=2, verbose_name='Class Type'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='description',
            field=tinymce.models.HTMLField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='duration',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='scheduled_on',
            field=models.DateTimeField(verbose_name='Scheduled On'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='seats',
            field=models.PositiveSmallIntegerField(default=150, verbose_name='Seats'),
        ),
    ]
