# Generated by Django 2.2.16 on 2021-08-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0006_auto_20210624_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='live_classes'),
        ),
    ]
