# Generated by Django 2.2.16 on 2021-08-24 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_organization', '0002_taleem_organization_verbose_name'),
        ('live_class', '0007_adding_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='taleem_organization.TaleemOrganization'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_classes', to='taleem_organization.Subject'),
        ),
    ]
