# Generated by Django 2.2.16 on 2021-08-27 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0008_adding_subject_and_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='grade',
            field=models.CharField(choices=[('NA', 'Not Applicable'), ('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3'), ('G4', 'Grade 4'), ('G5', 'Grade 5'), ('G6', 'Grade 6'), ('G7', 'Grade 7'), ('G8', 'Grade 8'), ('G9', 'Grade 9'), ('GA', 'Grade 10'), ('GB', 'Grade 11'), ('GC', 'Grade 12')], default='NA', max_length=2, verbose_name='Standard Code'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='language',
            field=models.CharField(choices=[('AR', 'Arabic'), ('EN', 'English')], default='AR', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='taleem_organization.TaleemOrganization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='live_classes', verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_classes', to='taleem_organization.Subject', verbose_name='Subject'),
        ),
    ]
