# Generated by Django 2.2.16 on 2021-09-01 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0009_adding_grade_and_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclasspaymenthistory',
            name='live_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_history', to='live_class.LiveClass'),
        ),
        migrations.AlterField(
            model_name='liveclasspaymenthistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_class_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liveclasspaymenthistory',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_usages_for_live_class', to='payment_gateway.Voucher'),
        ),
    ]
