# Generated by Django 2.2.16 on 2021-10-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0010_auto_20210901_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveclass',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='language',
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='subject',
        ),
    ]
