# Generated by Django 2.2.16 on 2022-09-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0011_remove_subject_grade_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclassattendance',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
