# Generated by Django 2.2.16 on 2022-09-27 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0012_auto_20220923_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='moderator',
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ('user_type', 'teacher'),
                    ('user__is_staff', True),
                    ('user__is_superuser', True),
                    _connector='OR'
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name='live_classes',
                to='taleem.Ta3leemUserProfile'
            ),
        ),
        migrations.AlterField(
            model_name='liveclassattendance',
            name='joined_at',
            field=models.DateTimeField(),
        ),
    ]
