# Generated by Django 2.2.16 on 2022-12-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0013_auto_20220927_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclassattendance',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
