# Generated by Django 2.2.16 on 2021-06-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_overviews', '0023_auto_20201216_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Filter Description')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Filter Categories',
                'verbose_name': 'Filter Category',
            },
        ),
        migrations.CreateModel(
            name='FilterCategoryValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('filter_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taleem_search.FilterCategory')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name_plural': 'Filter Category Values',
                'verbose_name': 'Filter Category Value',
            },
        ),
        migrations.CreateModel(
            name='CourseFilters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='course_overviews.CourseOverview')),
                ('filter_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_filters', to='taleem_search.FilterCategoryValue')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name_plural': 'Courses Filters',
                'verbose_name': 'Course Filters',
            },
        ),
    ]
