# Generated by Django 2.2.16 on 2021-06-29 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_search', '0002_auto_20210617_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercategory',
            name='weightage',
            field=models.FloatField(default=0.0, help_text='Weightage to get courses for filtration', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Category Weightage'),
        ),
    ]
