# Generated by Django 2.2.16 on 2021-08-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_search', '0003_filtercategory_weightage'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercategory',
            name='name_in_arabic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name in Arabic'),
        ),
        migrations.AddField(
            model_name='filtercategoryvalue',
            name='value_in_arabic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
