# Generated by Django 2.2.16 on 2021-10-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_search', '0004_auto_20210801_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercategoryvalue',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='taleem_search', verbose_name='Logo'),
        ),
    ]
