# Generated by Django 2.2.16 on 2021-10-19 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0010_auto_20210901_2257'),
        ('taleem_search', '0005_adding_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCourseFilters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='live_class.LiveClass')),
                ('filter_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_course_filters', to='taleem_search.FilterCategoryValue')),
            ],
            options={
                'verbose_name': 'Live Course Filter',
                'verbose_name_plural': 'Live Course Filters',
                'ordering': ('id',),
            },
        ),
    ]
