# Generated by Django 2.2.16 on 2022-04-08 12:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_search', '0011_auto_20220407_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercategory',
            name='special',
            field=models.BooleanField(default=False, help_text='pretend to have no sub categories'),
        ),
        migrations.AlterField(
            model_name='advertisedcourse',
            name='course',
            field=models.OneToOneField(default=None, limit_choices_to=models.Q(('is_timed_exam', 0), models.Q(('end_date__isnull', True), ('end_date__gt', datetime.datetime(2022, 4, 8, 12, 38, 43, 320079, tzinfo=utc)), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertised', to='course_overviews.CourseOverview'),
        ),
        migrations.AlterField(
            model_name='coursefilters',
            name='course',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('is_timed_exam', 0), models.Q(('end_date__isnull', True), ('end_date__gt', datetime.datetime(2022, 4, 8, 12, 38, 43, 320956, tzinfo=utc)), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='course_overviews.CourseOverview'),
        ),
    ]
