# Generated by Django 2.2.16 on 2022-04-18 09:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_search', '0012_special_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercategory',
            name='highlight',
            field=models.BooleanField(default=False, help_text='Show on mobile discover screen'),
        ),
        migrations.AlterField(
            model_name='advertisedcourse',
            name='course',
            field=models.OneToOneField(default=None, limit_choices_to=models.Q(('is_timed_exam', 0), models.Q(('end_date__isnull', True), ('end_date__gt', datetime.datetime(2022, 4, 18, 9, 6, 17, 426493, tzinfo=utc)), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertised', to='course_overviews.CourseOverview'),
        ),
        migrations.AlterField(
            model_name='coursefilters',
            name='course',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('is_timed_exam', 0), models.Q(('end_date__isnull', True), ('end_date__gt', datetime.datetime(2022, 4, 18, 9, 6, 17, 427372, tzinfo=utc)), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='course_overviews.CourseOverview'),
        ),
    ]
