# Generated by Django 2.2.16 on 2022-04-25 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0023_auto_20201216_0753'),
        ('taleem_search', '0013_highlight_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisedcourse',
            options={'ordering': ('-priority',), 'verbose_name': 'Advertised Course', 'verbose_name_plural': 'Advertised Courses'},
        ),
        migrations.AddField(
            model_name='advertisedcourse',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='advertisedcourse',
            name='course',
            field=models.OneToOneField(limit_choices_to=models.Q(('is_timed_exam', 0), models.Q(('end_date__isnull', True), ('end_date__gt', datetime.datetime(2022, 4, 25, 10, 53, 45, 7265, tzinfo=utc)), _connector='OR')), on_delete=django.db.models.deletion.CASCADE, related_name='advertised', to='course_overviews.CourseOverview'),
        ),
        migrations.AlterField(
            model_name='coursefilters',
            name='course',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('is_timed_exam', 0), models.Q(('end_date__isnull', True), ('end_date__gt', datetime.datetime(2022, 4, 25, 10, 53, 45, 9012, tzinfo=utc)), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='course_overviews.CourseOverview'),
        ),
        migrations.CreateModel(
            name='PopularCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('course', models.OneToOneField(limit_choices_to=models.Q(('is_timed_exam', 0), models.Q(('end_date__isnull', True), ('end_date__gt', datetime.datetime(2022, 4, 25, 10, 53, 45, 8185, tzinfo=utc)), _connector='OR')), on_delete=django.db.models.deletion.CASCADE, related_name='popular', to='course_overviews.CourseOverview')),
            ],
            options={
                'ordering': ('-priority',),
                'verbose_name': 'Popular Course',
                'verbose_name_plural': 'Popular Courses',
            },
        ),
    ]
