# Generated by Django 2.2.16 on 2022-06-17 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_search', '0014_popular_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisedcourse',
            name='course',
            field=models.OneToOneField(limit_choices_to=models.Q(('is_timed_exam', 0), models.Q(('end_date__isnull', True), ('end_date__gt', datetime.datetime(2022, 6, 17, 10, 25, 40, 274274, tzinfo=utc)), _connector='OR')), on_delete=django.db.models.deletion.CASCADE, related_name='advertised', to='course_overviews.CourseOverview'),
        ),
        migrations.AlterField(
            model_name='coursefilters',
            name='course',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('is_timed_exam', 0), models.Q(('end_date__isnull', True), ('end_date__gt', datetime.datetime(2022, 6, 17, 10, 25, 40, 276625, tzinfo=utc)), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='course_overviews.CourseOverview'),
        ),
        migrations.AlterField(
            model_name='popularcourse',
            name='course',
            field=models.OneToOneField(limit_choices_to=models.Q(('is_timed_exam', 0), models.Q(('end_date__isnull', True), ('end_date__gt', datetime.datetime(2022, 6, 17, 10, 25, 40, 275374, tzinfo=utc)), _connector='OR')), on_delete=django.db.models.deletion.CASCADE, related_name='popular', to='course_overviews.CourseOverview'),
        ),
    ]
