# Generated by Django 2.2.16 on 2022-12-02 11:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_search', '0015_auto_20220617_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisedcourse',
            name='course',
            field=models.OneToOneField(limit_choices_to=models.Q(('is_timed_exam', 0), models.Q(('end_date__isnull', True), ('end_date__gt', datetime.datetime(2022, 12, 2, 11, 17, 5, 246869, tzinfo=utc)), _connector='OR')), on_delete=django.db.models.deletion.CASCADE, related_name='advertised', to='course_overviews.CourseOverview'),
        ),
        migrations.AlterField(
            model_name='coursefilters',
            name='course',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('is_timed_exam', 0), models.Q(('end_date__isnull', True), ('end_date__gt', datetime.datetime(2022, 12, 2, 11, 17, 5, 248049, tzinfo=utc)), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='course_overviews.CourseOverview'),
        ),
        migrations.AlterField(
            model_name='popularcourse',
            name='course',
            field=models.OneToOneField(limit_choices_to=models.Q(('is_timed_exam', 0), models.Q(('end_date__isnull', True), ('end_date__gt', datetime.datetime(2022, 12, 2, 11, 17, 5, 247381, tzinfo=utc)), _connector='OR')), on_delete=django.db.models.deletion.CASCADE, related_name='popular', to='course_overviews.CourseOverview'),
        ),
    ]
