# Generated by Django 2.2.16 on 2023-01-20 04:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_search', '0016_auto_20221202_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisedcourse',
            name='course',
            field=models.OneToOneField(limit_choices_to=models.Q(('is_timed_exam', 0), models.Q(('end_date__isnull', True), ('end_date__gt', datetime.datetime(2023, 1, 20, 4, 31, 42, 660551, tzinfo=utc)), _connector='OR')), on_delete=django.db.models.deletion.CASCADE, related_name='advertised', to='course_overviews.CourseOverview'),
        ),
        migrations.AlterField(
            model_name='coursefilters',
            name='course',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('is_timed_exam', 0), models.Q(('end_date__isnull', True), ('end_date__gt', datetime.datetime(2023, 1, 20, 4, 31, 42, 661550, tzinfo=utc)), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='course_overviews.CourseOverview'),
        ),
        migrations.AlterField(
            model_name='popularcourse',
            name='course',
            field=models.OneToOneField(limit_choices_to=models.Q(('is_timed_exam', 0), models.Q(('end_date__isnull', True), ('end_date__gt', datetime.datetime(2023, 1, 20, 4, 31, 42, 661065, tzinfo=utc)), _connector='OR')), on_delete=django.db.models.deletion.CASCADE, related_name='popular', to='course_overviews.CourseOverview'),
        ),
    ]
