# Generated by Django 2.2.16 on 2021-02-06 13:44

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('role', models.CharField(choices=[('all', 'For All'), ('students', 'For Students'), ('teachers', 'For Teachers')], max_length=16)),
                ('title_english', models.CharField(max_length=255)),
                ('title_arabic', models.CharField(max_length=255)),
                ('description_english', tinymce.models.HTMLField(help_text='Describe the topic in English here.')),
                ('description_arabic', tinymce.models.HTMLField(help_text='Describe the topic in Arabic here.')),
                ('display_priority', models.IntegerField(default=0, help_text='Topic with higher number will be shown first.')),
            ],
            options={
                'ordering': ['-display_priority'],
                'db_table': 'taleem_help_topics',
                'verbose_name': 'Help Topics',
            },
        ),
    ]
