# Generated by Django 2.2.16 on 2021-03-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_adding_help_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helptopic',
            options={'ordering': ['-display_priority'], 'verbose_name': 'Help Topics', 'verbose_name_plural': 'Help Topics'},
        ),
    ]
