# Generated by Django 2.2.16 on 2020-12-27 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edx_proctoring', '0010_update_backend'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoredExamSessionConnectionHistory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_echo', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'index_together': {('course_id', 'user')},
            },
        ),
    ]
