# Generated by Django 2.2.16 on 2021-01-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_proctoring', '0012_proctoredexamtabswitchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoredexamstudentattempt',
            name='last_poll_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
