# Generated by Django 2.2.16 on 2021-01-22 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edx_proctoring', '0013_proctoredexamstudentattempt_last_poll_auto_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoredExamReview',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proctoring_proctoredexamstudentattemptreview',
                'verbose_name': 'proctored exam review',
            },
        ),
    ]
