# Generated by Django 2.2.16 on 2021-02-03 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edx_proctoring', '0014_proctoredexamreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoredExamSnapshot',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('snapshot', models.ImageField(upload_to='proctoring/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'proctored exam student snapshots',
                'db_table': 'proctoring_proctoredexamstudentsnapshot',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamWebMonitoringHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(max_length=255)),
                ('proctored_exam_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edx_proctoring.ProctoredExamSnapshot')),
            ],
            options={
                'verbose_name': 'proctored exam web monitoring history',
                'db_table': 'proctoring_proctoredexamwebmonitoringhistory',
            },
        ),
    ]
