# Generated by Django 2.2.16 on 2021-02-04 06:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edx_proctoring', '0015_proctoredexamsnapshot_proctoredexamwebmonitoringhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proctoredexamreview',
            unique_together={('course_id', 'user')},
        ),
    ]
