# Generated by Django 2.2.16 on 2021-02-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_proctoring', '0016_proctoredexamreview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoredexamwebmonitoringhistory',
            name='is_snapshot_recognized',
            field=models.BooleanField(default=False),
        ),
    ]
