# Generated by Django 2.2.16 on 2021-09-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_proctoring', '0017_proctoredexamwebmonitoringhistory_is_snapshot_recognized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoredexamstudentattempt',
            name='allowed_time_limit_mins',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proctoredexamstudentattempthistory',
            name='allowed_time_limit_mins',
            field=models.FloatField(null=True),
        ),
    ]
