# Generated by Django 2.2.16 on 2021-11-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_proctoring', '0018_allowed_time_mins_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoredexamstudentattempt',
            name='allow_entrance',
            field=models.BooleanField(default=False, verbose_name='Allow exam entrance'),
        ),
    ]
