# Generated by Django 2.2.16 on 2022-03-31 10:05

from django.db import migrations, models
import edx_proctoring.models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_proctoring', '0019_proctoredexamstudentattempt_allow_entrance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoredexamsnapshot',
            name='snapshot',
            field=models.ImageField(upload_to=edx_proctoring.models.ProctoredExamSnapshot.snapshot_file_name),
        ),
    ]
