# Generated by Django 2.2.16 on 2021-08-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmessage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
