# Generated by Django 2.2.16 on 2021-08-26 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openedx.custom.notifications.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_adding_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReminderSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('course_reminder_time', models.CharField(default='24 hours', help_text='Time to send the email before the course start date, course end date and any other important date like assignment or quiz or any section due date. Time should be in format like:  `10 mins` or `2 hours` or `2 days`. You can only set the min, hours and days', max_length=10, validators=[openedx.custom.notifications.models.validate_time_string], verbose_name='Course Reminder Time')),
                ('exam_reminder_time', models.CharField(default='24 hours', help_text='Time to send the email before the exam start date and exam end date. Time should be in format like:  `10 mins` or `2 hours` or `2 days`. You can only set the min, hours and days', max_length=10, validators=[openedx.custom.notifications.models.validate_time_string], verbose_name='Exam Reminder Time')),
                ('live_class_reminder_time', models.CharField(default='24 hours', help_text='Time to send the email before the live class start. Time should be in format like:  `10 mins` or `2 hours` or `2 days`. You can only set the min, hours and days', max_length=10, validators=[openedx.custom.notifications.models.validate_time_string], verbose_name='Live Class Reminder Time')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'ordering': ('-change_date',),
                'verbose_name_plural': 'Auto Notification Configurations',
                'verbose_name': 'Auto Notification Configuration',
                'abstract': False,
            },
        ),
    ]
