# Generated by Django 2.2.16 on 2022-08-08 14:01

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_eventremindersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmessage',
            name='course_key',
            field=opaque_keys.edx.django.models.CourseKeyField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationmessage',
            name='data',
            field=jsonfield.fields.JSONField(default=dict, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}),
        ),
    ]
