# Generated by Django 2.2.16 on 2022-12-20 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_add_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='receive_on',
            field=models.CharField(choices=[('wb', 'Web'), ('mb', 'Mobile'), ('bt', 'Both'), ('nw', 'Nowhere')], db_index=True, default='bt', max_length=2),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
