LMS_ROOT_URL: https://demo.openedx.dev
LMS_INTERNAL_ROOT_URL: ''
STATIC_ROOT_BASE: /openedx/edx-platform/static
STATIC_URL_BASE: /static/
ENABLE_COMPREHENSIVE_THEMING: true
COMPREHENSIVE_THEME_DIRS:
- '/openedx/edx-platform/themes'
DEFAULT_SITE_THEME: 'taleem-theme'
LOG_DIR: ''
DATA_DIR: /edx/var/edxapp
SECRET_KEY: dummy
AWS_ACCESS_KEY_ID: ''
AWS_SECRET_ACCESS_KEY: ''
DATABASES: {}
CACHES:
    default:
        BACKEND: django.core.cache.backends.memcached.MemcachedCache
        KEY_FUNCTION: util.memcache.safe_key
        KEY_PREFIX: default
        LOCATION:
        - localhost:11211
        VERSION: '1'
SITE_NAME: demo.openedx.dev
LOGGING_ENV: sandbox
FEATURES:
    PREVIEW_LMS_BASE: ''
XQUEUE_INTERFACE:
    basic_auth:
    - dummy
    - dummy
    django_auth:
        password: dummy
        username: lms
    url: http://localhost:18040
