# Generated by Django 2.2.16 on 2023-03-06 10:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edxval', '0002_add_error_description_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('edx_video_id', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid edx_video_id', message='edx_video_id has invalid characters', regex='^[a-zA-Z0-9\\-_]*$')])),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_video', to='edxval.Video')),
            ],
            options={
                'verbose_name': 'Public Video',
                'verbose_name_plural': 'Public Videos',
                'ordering': ('-created',),
            },
        ),
    ]
