# Generated by Django 2.2.16 on 2022-04-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_interactivexblock_utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='h5pextraction',
            name='index_page_path',
            field=models.CharField(default='h5p.json', max_length=255),
            preserve_default=False,
        ),
    ]
