# Generated by Django 2.2.16 on 2021-03-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verify_student', '0012_sspverificationretryconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSoftwareSecurePhotoVerification',
            fields=[
            ],
            options={
                'constraints': [],
                'proxy': True,
                'indexes': [],
            },
            bases=('verify_student.softwaresecurephotoverification',),
        ),
        migrations.CreateModel(
            name='StudentSoftwareSecurePhotoVerification',
            fields=[
            ],
            options={
                'constraints': [],
                'proxy': True,
                'indexes': [],
            },
            bases=('verification.customsoftwaresecurephotoverification',),
        ),
        migrations.CreateModel(
            name='TeacherSoftwareSecurePhotoVerification',
            fields=[
            ],
            options={
                'constraints': [],
                'proxy': True,
                'indexes': [],
            },
            bases=('verification.customsoftwaresecurephotoverification',),
        ),
    ]
