# Generated by Django 2.2.16 on 2021-11-04 06:50

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoVerificationVerifiedStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('submitted', 'Only Submission'), ('approved_by_ai', 'Verified By AI'), ('approved', 'Full Verified')], default='approved', help_text='Required verification status before allowing students access to the timed exam.', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Photo Verification Verified Status',
                'verbose_name_plural': 'Photo Verification Verified Statuses',
            },
        ),
    ]
