# Generated by Django 2.2.16 on 2022-02-16 22:02

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_photoverificationverifiedstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoVerificationVerifiedStatusForPublicTimeExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('allow', 'Allow Everyone'), ('submitted', 'Only Submission'), ('approved_by_ai', 'Verified By AI'), ('approved', 'Full Verified')], default='approved', help_text='Verification level before allowing students access to the timed exam.', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name_plural': 'Photo Verification Verified Statuses For Public Timed Exam',
                'verbose_name': 'Photo Verification Status For Public Timed Exam',
            },
        ),
        migrations.AlterModelOptions(
            name='photoverificationverifiedstatus',
            options={'verbose_name': 'Photo Verification Status For Private Timed Exam', 'verbose_name_plural': 'Photo Verification Verified Statuses For Private Timed Exam'},
        ),
        migrations.AlterField(
            model_name='photoverificationverifiedstatus',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='approved', help_text='Verification level before allowing students access to the timed exam.', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
