# Generated by Django 2.2.16 on 2022-12-02 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.encoder
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ta3leemEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email_type', models.CharField(max_length=255)),
                ('params', jsonfield.fields.JSONField(blank=True, default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True)),
                ('stage', models.CharField(choices=[('pd', 'Pending'), ('ok', 'Sent'), ('fl', 'Failed')], db_index=True, default='pd', max_length=2)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taleem_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ta3leem Email',
                'verbose_name_plural': 'Ta3leem Emails',
                'ordering': ('id',),
            },
        ),
    ]
