# Generated by Django 2.2.16 on 2021-09-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_ebooks_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookcategory',
            name='name_ar',
            field=models.CharField(default='خيالي', max_length=255),
            preserve_default=False,
        ),
    ]
