# Generated by Django 2.2.16 on 2021-09-16 06:03

from django.db import migrations, models
import openedx.custom.ebooks.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0003_ebooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='ebooks/cover', validators=[openedx.custom.ebooks.models.validate_cover_image], verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='pdf',
            field=models.FileField(max_length=255, upload_to=openedx.custom.ebooks.models.ebook_directory_path, validators=[openedx.custom.ebooks.models.validate_pdf_file]),
        ),
    ]
