# Generated by Django 2.2.16 on 2021-09-16 09:35

import django.core.validators
from django.db import migrations, models
import openedx.custom.ebooks.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0004_ebooks_validations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='cover',
            field=models.ImageField(upload_to='ebooks/cover', validators=[openedx.custom.ebooks.models.validate_cover_image], verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='pages',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of pages'),
        ),
    ]
