# Generated by Django 2.2.16 on 2021-02-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subject.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='TaleemOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the organization.', max_length=512)),
                ('type', models.CharField(choices=[('UNIVERSITY', 'University'), ('SCHOOL', 'School')], max_length=25)),
            ],
            options={
                'verbose_name': 'Taleem Organization',
                'verbose_name_plural': 'Taleem Organizations',
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the college.', max_length=512)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taleem_organization.TaleemOrganization')),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the department.', max_length=512)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taleem_organization.College')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'unique_together': {('name', 'college')},
            },
        ),
    ]
