# Generated by Django 2.2.16 on 2021-02-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taleemorganization',
            options={'verbose_name': 'Ta3leem Organization', 'verbose_name_plural': 'Ta3leem Organizations'},
        ),
    ]
