# Generated by Django 2.2.16 on 2021-11-26 06:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_organization', '0005_tashgeelauthtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255, unique=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taleem_organization.Skill')),
            ],
            options={
                'verbose_name': 'Course Skill',
                'verbose_name_plural': 'Course Skills',
                'unique_together': {('course_key', 'skill')},
            },
        ),
    ]
