# Generated by Django 2.2.16 on 2021-12-03 03:36

from django.db import migrations, models
import django.utils.timezone
import jsonfield.encoder
import jsonfield.fields
import model_utils.fields
import openedx.custom.taleem_organization.models


def add_tashgheel_config(apps, schema_editor):
    openedx.custom.taleem_organization.models.TashgheelConfig.objects.create()


def delete_tashgheel_config(apps, schema_editor):
    for obj in openedx.custom.taleem_organization.models.TashgheelConfig.objects.all():
        obj.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_organization', '0006_courseskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='TashgheelConfig',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='Tashgheel Config', help_text='Name of the Configuration, (Must be unique)', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('ip_addresses', jsonfield.fields.JSONField(blank=True, default=[], dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={})),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('token', models.CharField(default=openedx.custom.taleem_organization.models.token_generator, editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Tashgheel Configuration',
                'verbose_name_plural': 'Tashgheel Configurations',
            },
        ),
        migrations.RunPython(add_tashgheel_config, delete_tashgheel_config)
    ]
