# Generated by Django 2.2.16 on 2022-03-07 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_organization', '0007_tashgheelconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tashgeelauthtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
