# Generated by Django 2.2.16 on 2021-01-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedexamsettings',
            name='optional_easy_question_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timedexamsettings',
            name='optional_hard_question_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timedexamsettings',
            name='optional_medium_question_count',
            field=models.IntegerField(default=0),
        ),
    ]
