# Generated by Django 2.2.16 on 2021-01-19 08:51

from django.db import migrations, models
import django.utils.timezone
import jsonfield.encoder
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0002_auto_20210108_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimedExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('question_bank', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('allotted_time', models.CharField(default='01:00', max_length=255)),
                ('allowed_disconnection_window', models.CharField(default='01:00', max_length=255)),
                ('webcam_monitoring_mode', models.CharField(choices=[('detection', 'detection'), ('detection_and_recognition', 'detection_and_recognition')], max_length=255)),
                ('is_randomized', models.BooleanField(default=True)),
                ('easy_question_count', models.IntegerField(default=0)),
                ('optional_easy_question_count', models.IntegerField(default=0)),
                ('moderate_question_count', models.IntegerField(default=0)),
                ('optional_moderate_question_count', models.IntegerField(default=0)),
                ('hard_question_count', models.IntegerField(default=0)),
                ('optional_hard_question_count', models.IntegerField(default=0)),
                ('chapters', models.TextField(default='')),
                ('chapters_include_exclude', models.CharField(choices=[('all', 'All'), ('include', 'Include'), ('exclude', 'Exclude')], max_length=255)),
                ('topics', models.TextField(default='')),
                ('topics_include_exclude', models.CharField(choices=[('all', 'All'), ('include', 'Include'), ('exclude', 'Exclude')], max_length=255)),
                ('learning_output', models.TextField(default='')),
                ('learning_output_include_exclude', models.CharField(choices=[('all', 'All'), ('include', 'Include'), ('exclude', 'Exclude')], max_length=255)),
                ('metadata', jsonfield.fields.JSONField(default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='timedexamsettings',
            name='allowed_disconnection_window',
            field=models.CharField(default='01:00', max_length=255),
        ),
    ]
