# Generated by Django 2.2.16 on 2021-01-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0003_auto_20210119_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimedExamSettings',
        ),
    ]
