# Generated by Django 2.2.16 on 2021-02-05 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timed_exam', '0004_delete_timedexamsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedexam',
            name='num_easy_questions_pulled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timedexam',
            name='num_hard_questions_pulled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timedexam',
            name='num_moderate_questions_pulled',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('easy_questions', models.TextField(blank=True, null=True)),
                ('moderate_questions', models.TextField(blank=True, null=True)),
                ('hard_questions', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course_id', 'user')},
                'verbose_name': 'timed exam question set',
                'db_table': 'timed_exam_question_set',
            },
        ),
    ]
