# Generated by Django 2.2.16 on 2021-02-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0005_adding_question_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedexam',
            name='is_bidirectional',
            field=models.BooleanField(default=True),
        ),
    ]
