# Generated by Django 2.2.16 on 2021-02-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0006_timedexam_is_bidirectional'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedexam',
            name='user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
