# Generated by Django 2.2.16 on 2021-02-22 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timed_exam', '0007_timedexam_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedexam',
            name='external_exam_id',
            field=models.CharField(blank=True, help_text='Reference to the timed exam from external SIS module.', max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='PendingTimedExamUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_email', models.EmailField(max_length=254)),
                ('external_user_id', models.IntegerField(blank=True, db_index=True, help_text='Reference to user from external SIS module.', null=True)),
                ('timed_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timed_exam.TimedExam')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPendingTimedExamUser',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_email', models.EmailField(max_length=254)),
                ('external_user_id', models.IntegerField(blank=True, db_index=True, help_text='Reference to user from external SIS module.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('timed_exam', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='timed_exam.TimedExam')),
            ],
            options={
                'verbose_name': 'historical pending timed exam user',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='pendingtimedexamuser',
            constraint=models.UniqueConstraint(fields=('user_email', 'timed_exam'), name='unique user and TimedExam'),
        ),
    ]
