# Generated by Django 2.2.16 on 2021-03-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0009_timedexam_data_retention_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedexam',
            name='requires_seb',
            field=models.BooleanField(default=False),
        ),
    ]
