# Generated by Django 2.2.16 on 2021-11-11 06:06

from django.db import migrations, models
import django.db.models.deletion
from openedx.custom.taleem_organization.models import Skill

DEFAULT_SKILL_ID = 1
DEFAULT_SKILL_NAME = 'default-skill'


def create_default_skill(apps, schema_editor):
    """
    Create a default skill.
    """
    Skill.objects.get_or_create(id=DEFAULT_SKILL_ID, defaults={'name': DEFAULT_SKILL_NAME})


class Migration(migrations.Migration):

    dependencies = [
        ('taleem_organization', '0004_skill'),
        ('timed_exam', '0011_timedexamattempt'),
    ]

    operations = [
        migrations.RunPython(create_default_skill, migrations.RunPython.noop),
        migrations.AddField(
            model_name='timedexam',
            name='skill',
            field=models.ForeignKey(default=DEFAULT_SKILL_ID, on_delete=django.db.models.deletion.PROTECT, related_name='timed_exams', to='taleem_organization.Skill'),
            preserve_default=False,
        ),
    ]
