# Generated by Django 2.2.16 on 2021-11-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0012_timedexam_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedexam',
            name='enrollment_code',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='timedexam',
            name='generate_enrollment_code',
            field=models.BooleanField(default=False),
        ),
    ]
