# Generated by Django 2.2.16 on 2021-11-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0013_auto_20211124_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedexam',
            name='enrollment_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
