# Generated by Django 2.2.16 on 2021-12-02 07:43

from django.db import migrations, models
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0015_add_exam_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedexam',
            name='chapters',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='timedexam',
            name='learning_output',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='timedexam',
            name='metadata',
            field=jsonfield.fields.JSONField(blank=True, default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}),
        ),
        migrations.AlterField(
            model_name='timedexam',
            name='topics',
            field=models.TextField(blank=True, default=''),
        ),
    ]
