# Generated by Django 2.2.16 on 2021-12-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0016_fix_optional_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timedexam',
            name='webcam_monitoring_mode',
        ),
    ]
