# Generated by Django 2.2.16 on 2021-12-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0017_remove_unused_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedexam',
            name='mode',
            field=models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline')], default='ON', max_length=2, verbose_name='Mode of Examination'),
        ),
    ]
