# Generated by Django 2.2.16 on 2021-12-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0018_add_student_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedexam',
            name='enable_monitoring',
            field=models.BooleanField(default=True),
        ),
    ]
