# Generated by Django 2.2.16 on 2022-01-03 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0022_timedexamhide'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedexam',
            name='round',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
