# Generated by Django 2.2.16 on 2022-01-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0023_auto_20201216_0753'),
        ('timed_exam', '0023_timedexam_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedexam',
            name='linked_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timed_exams', to='course_overviews.CourseOverview'),
        ),
    ]
