# Generated by Django 2.2.16 on 2022-01-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0024_linked_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedexam',
            name='auto_enroll_from_linked_course',
            field=models.BooleanField(default=False),
        ),
    ]
