# Generated by Django 2.2.16 on 2022-01-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0025_auto_enroll_from_linked_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedexam',
            name='exam_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Invite only', 'Invite only')], default='Invite only', max_length=25, verbose_name='Timed exam type'),
        ),
    ]
