# Generated by Django 2.2.16 on 2022-02-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0026_timedexam_exam_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timedexam',
            name='auto_enroll_from_linked_course',
        ),
        migrations.RemoveField(
            model_name='timedexam',
            name='linked_course',
        ),
    ]
