# Generated by Django 2.2.16 on 2022-02-24 04:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0027_refactor_linked_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimedExamExtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('enrollment_password', models.CharField(help_text='Password that user will need to enroll in this private timed exam.', max_length=255)),
                ('timed_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='timed_exam.TimedExam')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
