# Generated by Django 2.2.16 on 2022-06-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0028_timedexamextras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timedexam',
            name='requires_seb',
        ),
    ]
