# Generated by Django 2.2.16 on 2022-07-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0029_remove_timedexam_requires_seb'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedexamhide',
            name='timed_exam_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timed_exam.TimedExam'),
        ),
    ]
