# Generated by Django 2.2.16 on 2022-07-24 20:11

from django.db import migrations


def link_timed_exam(apps, schema_editor):
    TimedExam = apps.get_model('timed_exam', 'TimedExam')
    TimedExamHide = apps.get_model('timed_exam', 'TimedExamHide')
    for exam_hide in TimedExamHide.objects.all():
        try:
            timed_exam = TimedExam.objects.get(key=exam_hide.timed_exam_id)
            exam_hide.timed_exam_link = timed_exam
            exam_hide.save()
        except TimedExam.DoesNotExist:
            exam_hide.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0030_timedexamhide_timed_exam_link'),
    ]

    operations = [
        migrations.RunPython(link_timed_exam),
        migrations.RemoveField(
            model_name='timedexamhide',
            name='timed_exam_id',
        ),
        migrations.RenameField(
            model_name='timedexamhide',
            old_name='timed_exam_link',
            new_name='timed_exam',
        ),
    ]
