# Generated by Django 2.2.16 on 2022-07-24 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0031_transfer_timed_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedexamhide',
            name='timed_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timed_exam.TimedExam'),
        ),
    ]
