# Generated by Django 2.2.16 on 2022-11-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timed_exam', '0032_auto_20220724_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTimedOutNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(db_index=True)),
            ],
        ),
    ]
