# Generated by Django 2.2.16 on 2021-03-26 13:43

from django.db import migrations, models
import django.utils.timezone
import lms.djangoapps.courseware.fields
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentExamGrade',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', lms.djangoapps.courseware.fields.UnsignedBigIntAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('percent_grade', models.FloatField()),
            ],
            options={
                'index_together': {('modified', 'course_id')},
                'unique_together': {('course_id', 'user_id')},
            },
        ),
    ]
