# Generated by Django 2.2.16 on 2020-11-04 07:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRating',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context_key', opaque_keys.edx.django.models.LearningContextKeyField(db_column='course_key', max_length=255)),
                ('block_key', opaque_keys.edx.django.models.UsageKeyField(max_length=255)),
                ('stars', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'index_together': {('context_key', 'block_key', 'user'), ('user', 'context_key', 'modified')},
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='VideoLike',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context_key', opaque_keys.edx.django.models.LearningContextKeyField(db_column='course_key', max_length=255)),
                ('block_key', opaque_keys.edx.django.models.UsageKeyField(max_length=255)),
                ('like', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'index_together': {('context_key', 'block_key', 'user'), ('user', 'context_key', 'modified')},
                'get_latest_by': 'modified',
            },
        ),
    ]
