# Generated by Django 2.2.16 on 2021-02-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_userprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='external_user_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Reference to user from external SIS module.', null=True),
        ),
    ]
