# Generated by Django 2.2.16 on 2021-02-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_userprofile_external_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Prefer Not to Say')], db_index=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('p', 'PHD'), ('m', "Master's degree"), ('hd', 'High Diploma'), ('b', "Bachelor's degree"), ('a', 'Diploma'), ('hs', 'High School'), ('jhs', 'Intermediate School'), ('el', 'Primary School'), ('pc', 'Professional Certificate'), ('none', 'No Certificates'), ('other', 'Other education')], db_index=True, max_length=6, null=True),
        ),
    ]
