# Generated by Django 2.2.16 on 2022-09-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_auto_20220829_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, choices=[('AN', 'Al Anbar'), ('BB', 'Babylon'), ('BG', 'Baghdad'), ('BA', 'Basra'), ('DQ', 'Dhi Qar'), ('QA', 'Al-Qādisiyyah'), ('DI', 'Diyala'), ('DA', 'Duhok'), ('AR', 'Erbil'), ('HA', 'Halabja'), ('KA', 'Karbala'), ('KI', 'Kirkuk'), ('MA', 'Maysan'), ('MU', 'Muthanna'), ('NA', 'Najaf'), ('NI', 'Nineveh'), ('SD', 'Saladin'), ('SU', 'Sulaymaniyah'), ('WA', 'Wasit')], max_length=20, null=True),
        ),
    ]
