# Generated by Django 2.2.16 on 2021-12-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_exam', '0001_add_student_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineexamstudentattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offlineexamstudentattempt',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offlineexamstudentattempt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
